In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent ))

# Libraries

In [2]:
from src.dominick import DominickDataLoader, DominickDataSaver
from src.eda import EDA

# Load Data

In [3]:
loader = DominickDataLoader()
df = loader.load("elasticity_features.csv")
df.head()

,category_code,upc_code,product_description,pack_size_text,units_per_case,product_item_code,store_code,week_id,units_sold,units_per_deal,...,price_per_liter,avg_price_per_liter,on_promo,promo_B,promo_C,promo_S,log_units_sold,log_price_per_upc,log_liters_sold,log_price_per_liter
0,27,294,BEER LIMIT,12/12O,2,9990180,2,298,11,1,...,0.6152,0.6152,False,0,0,0,2.397895,0.963174,3.846833,-0.485808
1,27,294,BEER LIMIT,12/12O,2,9990180,2,299,9,1,...,0.5894,0.5894,False,0,0,0,2.197225,0.920283,3.646162,-0.528650
2,27,294,BEER LIMIT,12/12O,2,9990180,2,300,6,1,...,0.5847,0.5847,False,0,0,0,1.791759,0.912283,3.240697,-0.536656
3,27,294,BEER LIMIT,12/12O,2,9990180,2,301,5,1,...,0.7021,0.7021,False,0,0,0,1.609438,1.095273,3.058376,-0.353679
4,27,294,BEER LIMIT,12/12O,2,9990180,2,302,1,1,...,0.5847,0.5847,False,0,0,0,0.000000,0.912283,1.448938,-0.536656

# EDA

In [4]:
eda = EDA()

In [5]:
eda.analyze_nans(df)

                      n_nans  pct_nans
category_code              0      0.00
upc_code                   0      0.00
units_per_case             0      0.00
product_item_code          0      0.00
store_code                 0      0.00
week_id                    0      0.00
units_sold                 0      0.00
units_per_deal             0      0.00
total_price                0      0.00
gross_margin_pct           0      0.00
exclude_flag               0      0.00
unit_price                 0      0.00
sales_dolar                0      0.00
gross_margin_rate          0      0.00
gross_margin_dolar         0      0.00
cost_dolar                 0      0.00
liters_per_upc         43229      1.08
price_per_upc              0      0.00
liters_sold            43229      1.08
price_per_liter        43229      1.08
avg_price_per_liter  2048318     51.33
promo_B                    0      0.00
promo_C                    0      0.00
promo_S                    0      0.00
log_units_sold       2020264     50.62
log_price_per_upc    2020406     50.63
log_liters_sold      2048318     51.33
log_price_per_liter  2048457     51.33

In [ ]:
eda.analyze_correlations(df_valid, "log_price_per_upc", "log_units_sold")

In [ ]:
eda.plot_correlations(eda.analyze_correlations(df_valid, "log_price_per_upc", "log_units_sold"))